# Generated by Django 4.2.6 on 2023-10-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_question_image_question_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='opt4',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
